/** Shared type exports. Domain definitions live in types/; existing imports stay valid. */
export type {
  Scalar,
  Cell,
  Column,
  DataFrameLike,
  DimensionIndexedTable,
  SeriesByKey,
  DfSets,
  ParameterTable,
  DfParameters,
  ScalarParameterData,
  ParameterData,
  DisplayUnits,
  ResultsTable,
  ScenarioResultsData,
} from './types/tables';
export type {
  ScenarioDataInput,
  ScenarioOptimization,
  ScenarioStatus,
  ScenarioResults,
  OverrideEntry,
  OverrideTable,
  ScenarioOverrides,
  Scenario,
  ScenarioMap,
  ScenarioId,
  ScenarioPropagation,
  OptimizationStart,
} from './types/scenario';
export type {
  MapUnits,
  CoordinateValue,
  MapFieldValue,
  MapCoordinates,
  MapFacilityFields,
  MapNode,
  ArcNodeRef,
  MapArc,
  ConnectionsMap,
  ConnectionMetadata,
  MapConnections,
  MapData,
  CoordinateTuple,
  MapEditorNode,
  MapContextData,
  SelectedNodeState,
  MapContextValue,
  MapProviderProps,
  MapAdditionalField,
} from './types/map';
export type {
  ConstraintViolationRecord,
  ConstraintViolationsSummary,
  ValidationSection,
  ScenarioValidation,
  ScenarioValidationResult,
  ValidationIssue,
  ScenarioFillPreview,
} from './types/validation';
export type {
  AIPromptUpdatedScenario,
  AIPromptResponse,
  AIOptimizationDiagnosisStep,
  AIOptimizationDiagnosisResponse,
  ScenarioAIDiagnosis,
  AISettings,
  AISettingsInput,
} from './types/ai';
export type {
  AppContextValue,
  AppState,
  AppAction,
  ModelResultsProps,
  SankeyPlotProps,
  KPIDashboardProps,
  OptimizationProps,
  NetworkDiagramProps,
  DataTableProps,
  DataInputProps,
  FilterDropdownProps,
  WaterQualityFilterDropdownProps,
  OverrideTableProps,
  OverrideTableRowsProps,
  NewOverrideRowProps,
  ComparisonTableProps,
  CustomChartProps,
  SubHeaderProps,
  SidebarProps,
  PopupModalProps,
  FileUploadModalProps,
  ScenarioCompareInputProps,
  ScenarioCompareOverridesProps,
  ScenarioCompareOutputProps,
  NetworkMapProps,
  InputSummaryProps,
  ScenarioCompareSidebarProps,
} from './types/components';
export type {
  ApiError,
  ApiResponse,
  ScenarioResponse,
  ScenarioListResponse,
  TaskResponse,
  CopyScenarioResponse,
  UpdateScenarioRequest,
  UpdateExcelRequest,
  RunModelRequest,
  FillScenarioInputsRequest,
} from './types/api';
